### ISSUE TITLE
Library of generic librares

### ISSUE THREAD

**Issue by jfontan** [src-d/go-borges#15]
There can be software that reads from two different library types like gitbase that can get repositories from plain directories or siva files. This library should have an `AddLibrary` method to add any library that implements `borges.Library`.

**Comment by jfontan** [comment]
This needs to be rethought as there may be problems with scheduling when mixing libraries. For example when using rooted repositories in sivas is better to schedule all repos in the same siva file together so the cache use is maximized. In the case of normal repos is better to alternate locations / libraries to use as many disks as possible.

**Comment by mcarmonaa** [comment]
Done in #21
