### ISSUE TITLE
[siva] Cleanup and add more testing

### ISSUE THREAD

**Issue by jfontan** [src-d/go-borges#4]

**Comment by mcarmonaa** [comment]
Done in:
- https://github.com/jfontan/go-borges/pull/12
- https://github.com/jfontan/go-borges/pull/13
- https://github.com/jfontan/go-borges/pull/14
- https://github.com/jfontan/go-borges/pull/15
- https://github.com/jfontan/go-borges/pull/16
- https://github.com/jfontan/go-borges/pull/17
- https://github.com/jfontan/go-borges/pull/19
