### ISSUE TITLE
Homogenize option arguments

### ISSUE THREAD

**Issue by jfontan** [src-d/go-borges#56]
In `plain` the option structs are passed as references but in `siva` they are values. Standardize options passing to references. Make sure that the options in the struct are copied so they can not be modified after setting them.

**Comment by mcarmonaa** [comment]
For library options we are using structs given to the constructors as a pointer to that struct (except for the siva.Library).

**Problem**
The problem if we want to ensure options can't be modified, it's that we need to copy the options values (derefencing the pointer). For plain types it's ok but for options which are pointers or interfaces we have to instantiate again other objects with the same conf than these ones.

**Solutions**
- Only pass plain options types, and instantiate whatever object is need in the constructor. For Example:

```go
// LibraryOptions hold configuration options for the library.
type LibraryOptions struct {
	Transactional bool
	Timeout time.Duration
	RegistryCache int
	TempFSPath string// instead of TempFS billy.Filesystem, then instantiate the billy.Filesystem
	Bucket int
	RootedRepo bool
	CacheSize // instead Cache cache.Object, if >0 then instantiate a specific cache.Object, we can't select which specific type. 
	Performance bool
}
```

- Just left a comment warning the API user to don't modify the options after they are used in a constructor. It's seems reasonable to don't modify them and normally the way we instantiate the libraries is:

```go
myLib := NewLibrary([...], &LibraryOpts{
        Opt1: foo,
        Opt2: bar,
})
```

so the options modification after they are given to a constructor shouldn't be a common case.

@jfontan wdyt?
