### ISSUE TITLE
Move library management to a new interface

### ISSUE THREAD

**Issue by jfontan** [src-d/go-borges#57]
We have a meta library in `libraries.Library`. This is able to register libraries to do operations on all of them. With this having the functionality in `plain` and `siva` to contain more libraries is redundant and error prone. I propose to move library management from standard `Library` to `MetaLibrary`:

```
type MetaLibrary interface {
	// Library returns the Library with the given LibraryID, if a library can't
	// be found ErrLibraryNotExists is returned.
	Library(LibraryID) (Library, error)
	// Libraries returns a LibraryIterator that iterates through all libraries
	// contained in this Library.
	Libraries() (LibraryIterator, error)
}
```

I'd also add a `Library()` function to `Locations` to be able to retrieve the library where they belong if needed.

**Comment by mcarmonaa** [comment]
If the only purpose of the interface will be having a collection of libraries, I'd call it `LibraryCollection` or whatever more descriptive name, `MetaLibrary` doesn't look explicit enough.

Also, maybe we should embed the `Library` interface here. Just like it is now, you can't handle it as a simple library so you must know the specific type conforms with `MetaLibrary` and `Library` interfaces. (Or maybe is what we want)

About the `Library()` method for `Locations`, I'm not sure if the case when you have a location but not the library it comes from, is really common. If you retrieved it from a `MetaLibrary` and it embed the `Library` interface, you could know the library with the `Has` method.

Anyway, if we would add the `Library()` method to the `Location` interface, we should think if it must return a `Library` or just a `LibraryID`

These are just a couple of thought I got at a first glance, so maybe there aren't really important and it works well as you propose.

**Comment by mcarmonaa** [comment]
After some discussion on slack we agreed to start with this and see how it evolves:
```
type Repository interface {
	ID() RepositoryID
	Location() Location
	Mode() Mode
	Commit(context.Context) error
	Close(context.Context) error
	R() *git.Repository
	FS() billy.Filesystem
}

type LibraryID string

type Library interface {
	ID() LibraryID
	Init(context.Context, RepositoryID) (Repository, error)
	Get(context.Context, RepositoryID, Mode) (Repository, error)
	GetOrInit(context.Context, RepositoryID) (Repository, error)
	Has(context.Context, RepositoryID) (bool, LibraryID, LocationID, error)
	Repositories(context.Context, Mode) (RepositoryIterator, error)
	Location(context.Context, LocationID) (Location, error)
	Locations(context.Context) (LocationIterator, error)
}

type LibraryCollection interface {
	Library

	Library(LibraryID) (Library, error)
	Libraries() (LibraryIterator, error)
}

type LocationID string

type Location interface {
	Library() Library
	ID() LocationID
	Init(context.Context, RepositoryID) (Repository, error)
	Get(context.Context, RepositoryID, Mode) (Repository, error)
	GetOrInit(context.Context, RepositoryID) (Repository, error)
	Has(context.Context, RepositoryID) (bool, error)
	Repositories(context.Context, Mode) (RepositoryIterator, error)
}
```
