### ISSUE TITLE
A "bad" siva file takes more than a day to be read

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/go-borges#86]
The following file: https://drive.google.com/file/d/1gUVRPoDDWPkSTEnF1UK8Ciahi1fFR-o2 takes more than a day to be read by go-borges and listed the files in each HEAD. Actually, I don't know the exact time it takes because I never waited longer than a day :) This is the **only** file in PGA which is so much retarded.

The code I run:

```
./list-pga-heads -lbash,cpp,csharp,go,java,javascript,php,python,ruby -n1 /directory/with/44e6ae3a44d73be5618daac6cc7785f08242817b.siva
```

where list-pga-heads is from https://github.com/src-d/datasets/tree/master/PublicGitArchive/list-pga-heads

**Comment by vmarkovtsev** [comment]
Interesting: if this file is in our ML cluster's GlusterFS, it is one day. If I copy this file on an SSD, it is less than 30 minutes.

**Comment by jfontan** [comment]
This repo has lots of references that slow down accessing them:

```
$ find refs | wc -l
220357
```

This may be fixed in the latest `go-siva` and `go-billy-siva` releases:

* https://github.com/src-d/go-siva/releases/tag/v1.7.0
* https://github.com/src-d/go-billy-siva/releases/tag/v4.6.0
